const lowerCamelCaseRegex = '^[a-z]+([A-Z0-9]*[a-z0-9]+[A-Za-z0-9]*)?$'

export default {
  plugins: ['stylelint-prettier', 'stylelint-order'],
  extends: ['stylelint-config-standard', 'stylelint-config-standard-scss'],
  ignoreFiles: ['public/**', 'src/assets/styles/cms/**'],
  rules: {
    'prettier/prettier': true,
    'block-no-empty': null,
    'rule-empty-line-before': [
      'always',
      {
        except: ['after-single-line-comment', 'first-nested'],
        ignore: ['after-comment'],
      },
    ],
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['first-nested', 'blockless-after-blockless'],
        ignore: ['after-comment'],
        ignoreAtRules: ['if', 'else', 'include'],
      },
    ],
    'declaration-empty-line-before': 'never',
    'length-zero-no-unit': true,
    'media-feature-range-notation': 'prefix',
    'alpha-value-notation': 'number',
    'selector-class-pattern': [
      '^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$',
      {
        message: (name) =>
          `Expected class name of "${name}" to match BEM pattern (e.g. .foo-block__bar-element--modifier)`,
      },
    ],
    'scss/dollar-variable-empty-line-before': [
      'always',
      { except: ['first-nested', 'after-comment', 'after-dollar-variable'] },
    ],
    'scss/double-slash-comment-empty-line-before': null,
    'scss/double-slash-comment-whitespace-inside': 'always',
    'keyframes-name-pattern': [
      lowerCamelCaseRegex,
      { message: () => 'Expected keyframe to be lower camel case' },
    ],
    'scss/dollar-variable-pattern': [
      lowerCamelCaseRegex,
      { message: () => 'Expected dollar variable to be lower camel case' },
    ],
    'scss/at-mixin-pattern': [
      lowerCamelCaseRegex,
      { message: () => 'Expected mixin to be lower camel case' },
    ],
    'scss/at-function-pattern': [
      lowerCamelCaseRegex,
      { message: () => 'Expected function to be lower camel case' },
    ],
    // disabled: rule can conflict with prettier line breaks that lead to new lines
    'scss/operator-no-newline-after': null,
    // disabled: gives false positives. E.g. NewsButton.scss $newsButtonThemeProps: ( --t-news-button: (...
    'custom-property-no-missing-var-function': null,
    /**
     * ORDER OF STYLE DECLARATIONS
     */
    'order/order': [
      {
        type: 'at-rule',
        name: 'use',
      },
      'custom-properties',
      'declarations',
      'rules',
      {
        type: 'at-rule',
        hasBlock: false,
      },
      {
        type: 'at-rule',
        name: 'include',
        parameter: new RegExp('mixins | newsMixins'),
      },
      // Stylelinter does not recognize if a mixin has media query. Since queries need to be beyond any other rules, you need to add them here manually.
      {
        type: 'at-rule',
        name: 'include',
        parameter: 'newsFonts',
      },
      {
        type: 'at-rule',
        name: 'include',
        parameter: 'breakpoints',
      },
      {
        type: 'at-rule',
        name: 'return',
      },
    ],
    'order/properties-order': [
      {
        unspecified: 'bottom',
        properties: [
          'pointer-events',
          'user-select',
          'cursor',
          'zoom',
          'resize',
          'content',
          'z-index',

          'visibility',
          'opacity',

          'position',
          'inset',
          'top',
          'right',
          'bottom',
          'left',

          'display',
          'float',
          'clear',
          'flex',
          'flex-grow',
          'flex-shrink',
          'flex-basis',
          'flex-direction',
          'flex-flow',
          'flex-wrap',
          'grid',
          'grid-area',
          'grid-template',
          'grid-template-areas',
          'grid-template-rows',
          'grid-template-columns',
          'grid-row',
          'grid-row-start',
          'grid-row-end',
          'grid-column',
          'grid-column-start',
          'grid-column-end',
          'grid-auto-rows',
          'grid-auto-columns',
          'grid-auto-flow',
          'place-content',
          'align-content',
          'justify-content',
          'place-items',
          'align-items',
          'justify-items',
          'place-self',
          'align-self',
          'justify-self',
          'order',
          'gap',
          'row-gap',
          'column-gap',
          'grid-gap',
          'grid-row-gap',
          'grid-column-gap',

          'container',
          'container-name',
          'container-type',

          'width',
          'height',
          'min-width',
          'min-height',
          'max-width',
          'max-height',
          'aspect-ratio',
          'overflow',
          'overflow-x',
          'overflow-y',
          'box-sizing',
          'object-fit',
          'object-position',

          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',

          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',

          'color',
          'font',
          'font-family',
          'font-size',
          'font-style',
          'font-weight',
          'font-variant',
          'font-size-adjust',
          'font-stretch',
          'font-effect',
          'font-emphasize',
          'font-emphasize-position',
          'font-emphasize-style',
          'font-smooth',
          'hyphens',
          'line-height',
          'text-align',
          'text-align-last',
          'text-emphasis',
          'text-emphasis-color',
          'text-emphasis-style',
          'text-emphasis-position',
          'text-decoration',
          'text-indent',
          'text-justify',
          'text-outline',
          'text-overflow',
          'text-overflow-ellipsis',
          'text-overflow-mode',
          'text-shadow',
          'text-transform',
          'text-wrap',
          'letter-spacing',
          'word-break',
          'word-spacing',
          'word-wrap',
          'white-space',
          'vertical-align',

          'background',
          'background-color',
          'background-image',
          'background-repeat',
          'background-attachment',
          'background-position',
          'background-position-x',
          'background-position-y',
          'background-clip',
          'background-origin',
          'background-size',

          'border',
          'border-color',
          'border-style',
          'border-width',
          'border-top',
          'border-top-color',
          'border-top-style',
          'border-top-width',
          'border-right',
          'border-right-color',
          'border-right-style',
          'border-right-width',
          'border-bottom',
          'border-bottom-color',
          'border-bottom-style',
          'border-bottom-width',
          'border-left',
          'border-left-color',
          'border-left-style',
          'border-left-width',
          'border-radius',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-bottom-right-radius',
          'border-bottom-left-radius',
          'border-image',
          'border-image-source',
          'border-image-slice',
          'border-image-width',
          'border-image-outset',
          'border-image-repeat',

          'outline',
          'outline-width',
          'outline-style',
          'outline-color',
          'outline-offset',

          'fill',
          'fill-opacity',
          'stroke',
          'stroke-opacity',
          'stroke-width',
          'shape-rendering',
          'clip',
          'text-anchor',
          'dominant-baseline',
          'paint-order',

          'transition',
          'transition-delay',
          'transition-timing-function',
          'transition-duration',
          'transition-property',
          'transform',
          'transform-origin',

          'animation',
          'animation-name',
          'animation-duration',
          'animation-fill-mode',
          'animation-play-state',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',

          'box-shadow',
          'filter',
        ],
      },
    ],
  },
}
